### ISSUE TITLE
Jornada intensiva de verano

### ISSUE THREAD

**Issue by carloscoches** [diazdavid-info/sesametime#1]
https://github.com/diazdavid-info/sesametime/blob/2396e3dcaf639bab71b95df8ae26bb6e2dad2cc7/src/exec.sh#L185

hasta septiembre, puedes cambiar la ejecución de lunes a juevas por special_flow (para que fiche de 8:00 a 15:00) ;)

**Comment by diazdavid-info** [comment]
He subido la versión 2.0.0. En esta versión se le puede pasar, al contenedor, una env más indicando si es "summer schedule".
La env es: SUMMER_SCHEDULE=("yes" || "no").
Con eso ya debería empezar a funcionar el horario de verano.

Nueva imagen de docker `diazdavid/sesametime:2.0.0`
